set(command "C:/Users/Aden/Desktop/cmake-3.10.2-win64-x64/bin/cmake.exe;-P;C:/A_PCL/RenderEngine/Horde3D/project_glfw-prefix/src/project_glfw-stamp/download-project_glfw.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "C:/Users/Aden/Desktop/cmake-3.10.2-win64-x64/bin/cmake.exe;-P;C:/A_PCL/RenderEngine/Horde3D/project_glfw-prefix/src/project_glfw-stamp/verify-project_glfw.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "C:/Users/Aden/Desktop/cmake-3.10.2-win64-x64/bin/cmake.exe;-P;C:/A_PCL/RenderEngine/Horde3D/project_glfw-prefix/src/project_glfw-stamp/extract-project_glfw.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
